In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[0])


1


In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [5]:
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array1d)

print("-" * 10)
print(array2d)
print("-" * 10)
print(array3d) 

[1 2 3 4 5 6]
----------
[[1 2 3]
 [4 5 6]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [6]:

thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(3, 3)
print(thearray)


[1 2 3 4]
----------
[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 0]]


#### shape of numpy array

In [7]:
 
array1d = np.array([1, 2, 3, 4, 5, 6])
array2d = np.array([[1, 2, 3], [4, 5, 6]])
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
 
print(array1d.shape)
print(array2d.shape)
print(array3d.shape)



(6,)
(2, 3)
(2, 2, 3)


#### Resize array

In [8]:
 
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(2, 4)
print(thearray)
 
print("-" * 10)
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray.resize(3, 3)
print(thearray)

[1 2 3 4]
----------
[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2 3]
 [4 5 6]
 [7 8 0]]


#### Reshape array


In [9]:
 
thearray = np.array([1, 2, 3, 4, 5, 6, 7, 8])
thearray = thearray.reshape(2, 4)
print(thearray)
 
print("-" * 10)
thearray = thearray.reshape(4, 2)
print(thearray)
 
print("-" * 10)
thearray = thearray.reshape(8, 1)
print(thearray)

[[1 2 3 4]
 [5 6 7 8]]
----------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [10]:
array1d = np.array([1, 2, 3, 4, 5, 6]) 
print(array1d[-1])   
print("-" * 10)
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)
print("-" * 10)
print(array2d[0, 0])   # Get first row first col 

6
----------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
1


In [11]:
array1d = np.zeros(3)
print(array1d)
 
array2d = np.zeros((2, 4))
print(array2d)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
import numpy as np
array1d = np.arange(5)  
print(array1d)
array1d = np.arange(0, 12, 2)  
print(array1d)
array2d = np.arange(0, 12, 2).reshape(2, 3)   
print(array2d) 

[0 1 2 3 4]
[ 0  2  4  6  8 10]
[[ 0  2  4]
 [ 6  8 10]]


In [13]:
print(np.random.rand(3, 2))   
   

[[0.94248312 0.76188395]
 [0.1143521  0.90075872]
 [0.46563954 0.01107728]]


In [14]:
print(np.identity(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(np.diag(np.arange(0, 8, 2)))

[[0 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]]


In [16]:
print(np.diag(np.diag(np.arange(9).reshape((3,3)))))

[[0 0 0]
 [0 4 0]
 [0 0 8]]


In [17]:
array1 = np.array([[10, 20, 30], [14, 24, 36]])
array2 = np.array([[20, 40, 50], [24, 34, 46]])
 
print(np.union1d(array1, array2))
  

[10 14 20 24 30 34 36 40 46 50]


In [18]:
array1 = np.array([[10, 20, 30], [14, 24, 36]])
array2 = np.array([[20, 40, 50], [24, 34, 46]])
print(np.intersect1d(array1, array2))

[20 24]


In [19]:
array1 = np.array([[10, 20, 30], [14, 24, 36]])
array2 = np.array([[20, 40, 50], [24, 34, 46]])
print(np.setdiff1d(array1, array2))
 

[10 14 30 36]


In [20]:
before = np.array([[0, 1, 2], [2, 0, 1], [1, 2, 0]])
choices = [5, 10, 15]
 
after = np.choose(before, choices)
print(after)
 
print("-" * 10)
 
before = np.array([[0, 0, 0], [2, 2, 2], [1, 1, 1]])
choice1 = [5, 10, 15]
choice2 = [8, 16, 24]
choice3 = [9, 18, 27]
 
after = np.choose(before, (choice1, choice2, choice3))
print(after)

[[ 5 10 15]
 [15  5 10]
 [10 15  5]]
----------
[[ 5 10 15]
 [ 9 18 27]
 [ 8 16 24]]


In [21]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
 
print(np.sin(array1))


[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]


In [22]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print(np.cos(array1))

[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]


In [23]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print(np.tan(array1)) 



[[ 0.64836083  2.23716094 -6.4053312 ]
 [-1.11721493 -0.27190061  0.32004039]]


In [24]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print(np.sqrt(array1))


[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [25]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print(np.exp(array1))


[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [46]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print(np.log10(array1))


[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]


In [47]:
array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array3d)
 
print(array3d[0, 0, 0])
print(array3d[0, 0, 1])
print(array3d[0, 0, 2])
  

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3


In [48]:
type1 = np.array([1, 2, 3, 4, 5, 6])
type2 = np.array([1.5, 2.5, 0.5, 6])
type3 = np.array(['a', 'b', 'c'])
type4 = np.array(["Canada", "Australia"], dtype='U5')
type5 = np.array([555, 666], dtype=float)
 
print(type1.dtype)
print(type2.dtype)
print(type3.dtype)
print(type4.dtype)
print(type5.dtype)
 

int32
float64
<U1
<U5
float64


In [49]:
print(np.linspace(1, 10))  
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [40]:
x = np.array(42)
print("x: ", x)
print("The type of x: ", type(x))
print("The dimension of x:", np.ndim(x))

x:  42
The type of x:  <class 'numpy.ndarray'>
The dimension of x: 0


In [52]:
E = np.ones((2,3))
print(E)

F = np.ones((3,4),dtype=int)
print(F)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [55]:
x = np.array([[42,22,12],[44,53,66]], order='F')
y = x.copy()

x[0,0] = 1001
print(x)

print(y)

[[1001   22   12]
 [  44   53   66]]
[[42 22 12]
 [44 53 66]]


In [56]:
a = np.array([3,8,12,18,7,11,30])
odd_elements = a[1::2]
print(odd_elements)

[ 8 18 11]


In [57]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [58]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [59]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [60]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [61]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]
